Make *rx_buffer const
The capp to rp_SPI_GetRxBuffer() expects the buffer to be const. Without
the const qualifier the code will not compile.

```
cc -g -std=gnu11 -Wall -Werror -I/opt/redpitaya/include -I/root/dev/RedPitaya/build/include  -L/opt/redpitaya/lib -L/root/dev/RedPitaya/build/lib  spi_loopback.c  -static -lrp-hw -lrp -lm -lstdc++ -lpthread -o spi_loopback
spi_loopback.c: In function ‘main’:
spi_loopback.c:58:32: error: passing argument 2 of ‘rp_SPI_GetRxBuffer’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     res = rp_SPI_GetRxBuffer(0,&rx_buffer,&rx_size); // Get pointer to rx buffer. No need free buffer. Api itself destr
                                ^
In file included from spi_loopback.c:14:0:
/root/dev/RedPitaya/build/include/rp_hw.h:377:5: note: expected ‘const uint8_t ** {aka const unsigned char **}’ but argument is of type ‘uint8_t ** {aka unsigned char **}’
 int rp_SPI_GetRxBuffer(size_t msg,const uint8_t **buffer,size_t *len);
     ^
```

That the buffer needs to be const is shown in the `rp_hw.h` file:

```
int rp_SPI_GetRxBuffer(size_t msg,const uint8_t **buffer,size_t *len);
```